---
title: "prop18"
author: "Austin Chen"
date: "9/15/2020"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
install.packages("tidyverse")
library(magrittr)
library(tidyverse)
library(readxl)
```
```{r}
table01 = read_excel("table01.xlsx")
```


```{r}
table01 = table01[, -1]
```

```{r}
table01 = table01[-c(1:6),]
```

```{r}
colnames(table01)
```

```{r}
voter_data = table01
```

```{r}
#View(voter_data)
```


```{r}
voter_data = voter_data %>% 
  rename(
    Age = ...2,
    Total_Population = ...3,
    Total_Citizen_Population = ...4,
    Reported_Registered_Number = ...5,
    Reported_Registered_Percent = ...6,
    Reported_Not_Registered_Number = ...7,
    Reported_Not_Registered_Percent = ...8,
    No_Response_Registration_Number = ...9,
    No_Response_Registration_Percent = ...10,
    Reported_Voted_Number = ...11,
    Reported_Voted_Percent = ...12,
    Reported_Not_Voted_Number = ...13,
    Reported_Not_Voted_Number_Percent = ...14,
    No_Response_Voted_Number = ...15,
    No_Response_Voted_Percent = ...16, 
    Total_Population_Reported_Registered_Percent = ...17,
    Total_Population_Report_Voting_Percent = ...18
    
    
    )
```

```{r}
#View(voter_data)
```

```{r}
voter_data = voter_data[-c(217:223),]
```

```{r}
glimpse(voter_data)
```

```{r}
voter_data[, c(2:17)] <- sapply(voter_data[, c(2:17)], as.numeric)
```

```{r}
both_sexes_data = voter_data[c(1:72),]
```

```{r}
glimpse(both_sexes_data)
```


```{r}
head(both_sexes_data)
```

```{r}
male_data = voter_data[c(73:144),]
```

```{r}
glimpse(male_data)
```

```{r}
head(male_data)
```

```{r}
female_data = voter_data[c(145:216),]
```

```{r}
glimpse(female_data)
```

```{r}
head(female_data)
```



```{r}
summary(voter_data[, c(2:17)])
```
```{r}
#View(both_sexes_data)
```

```{r}
library(ggplot2)
```


```{r}
both_sexes_data$Age[c(9:70)] <- gsub(" years", " " , both_sexes_data$Age[c(9:70)] )
```

```{r}
#View(both_sexes_data)
```

```{r}
glimpse(both_sexes_data)
```
```{r}
both_sexes_data = both_sexes_data[-c(1:8),]

```

```{r}
both_sexes_data = both_sexes_data[-c(63:64),]
```

```{r}
both_sexes_data$Age <- sapply(both_sexes_data$Age, as.numeric)
```

```{r}
glimpse(both_sexes_data$Age[c(9:70)])
```



```{r}
both_sexes_data %>% 
  ggplot(aes(x = Age , y = Reported_Voted_Number)) + geom_line(color = "blue") +ggtitle("Age vs. Number of People Voted in 2018")
```
```{r}
both_sexes_data %>% 
  ggplot(aes(x = Age , y = Reported_Voted_Number)) + geom_point(color = "orange") +ggtitle("Age vs. Number of People Voted in 2018")
```

```{r}
library(corrplot)
```
```{r}
both_sexes_data %>% 
  ggplot(aes(x = Age , y = Reported_Registered_Percent)) + geom_point(color = "purple") +ggtitle("Age vs. Percentage of People Registered to Vote in 2018")
```



```{r}
both_sexes_data_matrix = as.matrix(both_sexes_data)
corrplot(cor(both_sexes_data_matrix, use="pairwise.complete.obs"), is.corr = FALSE, method = "circle", type = "lower")
```

```{r}
qplot(both_sexes_data$Age, both_sexes_data$Reported_Voted_Percent, main = "Plot of Age vs. Reported Voted Percent", xlab = "Age", ylab = "Reported Voted Percent", colour = both_sexes_data$Age) 
```

```{r}
qplot(both_sexes_data$Age, both_sexes_data$Reported_Not_Voted_Number, main = "Plot of Age vs. Reported Not Voted Number in thousands", xlab = "Age", ylab = "Reported Not Voted Number in thousands", colour = both_sexes_data$Age) 
```

```{r}
#remove.packages(c("highcharter", "data.table"))
#install.packages('highcharter')
#install.packages('data.table')
library(highcharter)
```

```{r}
hchart(both_sexes_data, "scatter", hcaes(x = Age, y = Reported_Voted_Percent))  
```
